name = "example"
main = "build/worker/shim.mjs"
compatibility_date = "2024-04-19"

[vars]
VAR = "my_variable"

[[kv_namespaces]]
binding = "KV"
id      = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[durable_objects.bindings]]
name       = "ROOMS"
class_name = "Room"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }
