name: CI
on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: check buildability
        run:  cargo check

      - name: check example
        working-directory: example
        run:  cargo check